name: dartbug
description: application to reproduce inconsistent generic type functions.

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
  test: any
